# ====================================================
# Aggregation Configuration File
# ====================================================
# This YAML configuration is used to run the aggregation mode.
# It specifies the input file containing all the processed statistics,
# the columns by which the data should be grouped/aggregated, and
# the output path for saving the aggregated results.

# ------------------------
# Input Data File
# ------------------------
input_file: "../input_files/modelb-T2M.data"       # Path to the processed input data file containing all statistics

# ------------------------
# Grouping Settings
# ------------------------
group_by: ["fcst_lead"]            # List of columns used for aggregation.
         
# The order determines how the data is grouped.

stats:
    - 'rmse'
    - 'bias'

# ------------------------
# Output Data File
# ------------------------
output_agg_file: "agg.data"   # Path and filename to save the aggregated data
